---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Deep surv}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(ReSurv)

```

```{r}
# Input data

input_data <- data_generator(random_seed = 1,
                              scenario=2,
                              time_unit = 1/360,
                              years = 4,
                              yearly_exposure = 200)


```

# Without calendar component (same as before, notice new inputs)

```{r}
# # # ## Model fit ----
  individual_data <- IndividualData(data = input_data,
                                    id=NULL,
                                    categorical_features = c("claim_type"),
                                    continuous_features = "AP",
                                    accident_period="AP",
                                    calendar_period="RP",
                                    input_time_granularity = "days",
                                    output_time_granularity = "quarters",
                                    years=4 #check this. I see strange development periods
  )
  

```

```{r}
# Model fit ----
resurv.fit.cox <- ReSurv(individual_data,
                          hazard_model = "cox")

```


```{r}

ooslkh(resurv.fit.cox)

```

```{r}

resurv.cox.predictions <- predict(resurv.fit.cox)

```

```{r}

individual_data2 <- IndividualData(input_data,
                                  id=NULL,
                                  continuous_features="AP",
                                  categorical_features="claim_type",
                                  accident_period="AP",
                                  calendar_period="RP",
                                  input_time_granularity = "days",
                                  output_time_granularity = "years",
                                  years=4,
                                  calendar_period_extrapolation=F)


resurv.cox.predictions <- predict(resurv.fit.cox,
                                  newdata=individual_data2)

```

```{r}

# # # ## Model fit ----
s1 <- Sys.time()
resurv.fit.xgb <- ReSurv(individual_data,
                         hazard_model = "xgboost",
                         hparameters = list(params=list(booster="gbtree",
                                             eta=.01,
                                             subsample=.5,
                                             alpha=1,
                                             lambda=1,
                                             min_child_weight=.2),
                                             print_every_n = 1,
                                             nrounds=10,
                                             verbose=F,
                                             early_stopping_rounds = 500))
e1 <- Sys.time()
e1-s1
```
```{r}
ooslkh(resurv.fit.xgb)
```



```{r}
# Model fit ----
resurv.fit.LTRCtrees <- ReSurv(individual_data,
                               hazard_model = "LTRCtrees")

```

```{r}
ooslkh(resurv.fit.LTRCtrees)
```


```{r}
s1 <- Sys.time()
resurv.fit.deepsurv <- ReSurv(individual_data,
                              hazard_model = "deepsurv",
                              hparameters=list(num_layers=c(10),
                                              early_stopping = TRUE,
                                              patience = 50,
                                              verbose=T,
                                              network_structure = NULL,
                                              num_nodes = c(10),
                                              activation = "LeakyReLU",
                                              optim="Adam",
                                              lr = 0.005,
                                              xi=0.480269023349308,
                                              epsilon = 0,
                                              batch_size=as.integer(5000),
                                              epochs=as.integer(2),
                                              num_workers=0,
                                              tie='Efron'))

e1 <- Sys.time()


```
```{r}
ooslkh(resurv.fit.deepsurv)

```

# Some plots


```{r}

#Plot different development factors

resurv.cox.predictions <- predict(resurv.fit.cox,grouping_method="probability")
resurv.deepsurv.predictions <- predict(resurv.fit.deepsurv,grouping_method="probability")
resurv.LTRCtrees.predictions <- predict(resurv.fit.LTRCtrees,grouping_method="probability")
resurv.xgb.predictions <- predict(resurv.fit.xgb,grouping_method="probability")

df_output_combined <- bind_rows(
  resurv.cox.predictions$df_output %>%
    reshape2::melt(id.vars="DP_o") %>% 
    mutate(Model="Cox"),
    resurv.deepsurv.predictions$df_output %>% reshape2::melt(id.vars="DP_o") %>% 
    mutate(Model="DeepSurv"),
    resurv.LTRCtrees.predictions$df_output %>% reshape2::melt(id.vars="DP_o") %>% 
    mutate(Model="LTRCTrees"),
    resurv.xgb.predictions$df_output %>% reshape2::melt(id.vars="DP_o") %>% 
    mutate(Model="XgBoost"),
) %>% rowwise() %>% 
  mutate(
    AP_o =  substr(variable,
                     unlist(gregexpr('_', variable))[2] +1,
                     unlist(gregexpr('\\,', variable))[1]-1 ),
    claim_type = substr(variable, nchar(as.character(variable)), nchar(as.character(variable)))
  ) %>% 
  ungroup() %>% 
  mutate(relevant=ifelse(AP_o==10, 1,0)) %>% 
  arrange(desc(relevant)) %>% 
  mutate(col=ifelse(relevant==1, Model, "Other accident periods of models")) %>% 
  mutate(col= factor(col,levels=c("Other accident periods of models","Cox", "DeepSurv", "XgBoost", "LTRCTrees" ) )) %>% 
  mutate(alpha=factor(paste0(Model,AP_o)))

alpha_vector <- df_output_combined %>%  group_by(alpha) %>%  summarize(relevant=sum(relevant)) %>% 
  mutate(alpha_value = ifelse(relevant>0,1,0.4))

p <- ggplot(data=df_output_combined) + geom_line(aes(x=DP_o, y=value, colour=col, linetype=claim_type, alpha=alpha)) +
  scale_linetype_manual(name = "", values=c(1,2), labels = c("Claim type 0","Claim type 1" ))+ 
  scale_colour_manual( values=c(
    c("grey","red","green","blue","orange")
    ),
    name =""
    )+
  scale_alpha_manual(
    values=c(alpha_vector$alpha_value),
    guide="none"
  )+
  ggtitle("Simulation 2 development factor comparison") +
  xlab("Quarterly development period") + ylab("Development factor")+
  guides(col = guide_legend(reverse=T)) +
  theme_bw() +
  theme(legend.position=c(0.8,0.7),
        plot.title = element_text(hjust = 0.5,size = 10, face = "bold"),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.spacing.y = unit(0, "mm"),
        legend.background = element_blank(),
        legend.title = element_blank(),
        legend.box.background = element_rect(colour = "black"))
  
p




```

```{r eval=FALSE, include=FALSE}


#Plot survival curves

columns <- sample.int((ncol(resurv.cox.predictions$df_input)-1)/2,50)
columns <-as.integer(c(columns, columns+1))

s_input_combined <- bind_rows(
  resurv.cox.predictions$df_input[,c(columns, ncol(resurv.cox.predictions$df_input)) ] %>%
    reshape2::melt(id.vars="DP_i") %>% 
    mutate(Model="Cox"),
    resurv.deepsurv.predictions$df_input[,c(columns, ncol(resurv.cox.predictions$df_input)) ] %>% reshape2::melt(id.vars="DP_i") %>% 
    mutate(Model="DeepSurv"),
    resurv.LTRCtrees.predictions$df_input[,c(columns, ncol(resurv.cox.predictions$df_input)) ] %>% reshape2::melt(id.vars="DP_i") %>% 
    mutate(Model="LTRCTrees"),
    resurv.xgb.predictions$df_input[,c(columns, ncol(resurv.cox.predictions$df_input)) ] %>% reshape2::melt(id.vars="DP_i") %>% 
    mutate(Model="XgBoost"),
) %>% data.table()

s_input_combined[,AP_i:=gsub(".*_.*_(.*)[,].*", "\\1", variable)]
s_input_combined[,claim_type:=gsub(".*_.*_.*_(.*)", "\\1", variable)]

selected <- sample(unique(s_input_combined$AP_i),1)

s_input_combined <- s_input_combined %>%  group_by(AP_i, claim_type) %>% 
  arrange(desc(DP_i)) %>% 
  mutate(S_i = 1/cumprod(value))

s_input_combined <-s_input_combined %>% 
  mutate(relevant=ifelse(AP_i==selected, 1,0)) %>% 
  arrange(desc(relevant)) %>% 
  mutate(col=ifelse(relevant==1, Model, "Other accident periods of models")) %>% 
  mutate(col= factor(col,levels=c("Other accident periods of models","Cox", "DeepSurv", "XgBoost", "LTRCTrees" ) )) %>% 
  mutate(alpha=factor(paste0(Model,AP_i)))

alpha_vector <- s_input_combined %>%  group_by(alpha) %>%  summarize(relevant=sum(relevant)) %>% 
  mutate(alpha_value = ifelse(relevant>0,1,0.4))

p2 <- ggplot(data=s_input_combined) + geom_line(aes(x=DP_i, y=S_i, colour=col, linetype=claim_type, alpha=alpha)) +
  scale_linetype_manual(name = "", values=c(1,3), labels = c("Claim type 0","Claim type 1" ))+ 
  scale_colour_manual( values=c(
    c("grey","red","green","blue","orange")
    ),
    name =""
    )+
  scale_alpha_manual(
    values=c(alpha_vector$alpha_value),
    guide="none"
  )+
  ggtitle("Simulation 2 Survival Curves") +
  xlab("t, Daily development period") + ylab("S(t), Survival probability")+
  guides(col = guide_legend(reverse=T)) +
  theme_bw() +
  theme(legend.position=c(0.8,0.3),
        plot.title = element_text(hjust = 0.5,size = 10, face = "bold"),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.spacing.y = unit(0, "mm"),
        legend.background = element_blank(),
        legend.title = element_blank(),
        legend.box.background = element_rect(colour = "black"))
  
p2


```

```{r}

#Plot ability to capture accident period dependency for development factors
#Only for a single model

df_output_combined <- bind_rows(
    resurv.LTRCtrees.predictions$df_output %>% reshape2::melt(id.vars="DP_o") %>% 
    mutate(Model="LTRCTrees")
) %>% rowwise() %>% 
  mutate(
    AP_o =  gsub(".*_.*_(.*)[,].*", "\\1", variable),
    claim_type = gsub(".*_.*_.*_(.*)", "\\1", variable)
  ) %>% 
  ungroup() %>% 
  mutate(relevant=case_when(
    as.numeric(AP_o) == min(as.numeric(df_output_combined$AP_o)) ~1,
    as.numeric(AP_o) == max(as.numeric(df_output_combined$AP_o)) ~2,
    TRUE   ~0 )) %>% 
  arrange(desc(relevant)) %>% 
    mutate(col=case_when(
    as.numeric(AP_o) == min(as.numeric(df_output_combined$AP_o)) ~"Initial accident period",
    as.numeric(AP_o) == max(as.numeric(df_output_combined$AP_o))  ~"Last accident period",
    TRUE   ~"Other accident periods of LTRCTrees" ))  %>% 
  mutate(col= factor(col,levels=c("Other accident periods of LTRCTrees","Last accident period", "Initial accident period" ) )) %>% 
  mutate(alpha=factor(paste0(Model,AP_o)))

alpha_vector <- df_output_combined %>%  group_by(alpha) %>%  summarize(relevant=sum(relevant)) %>% 
  mutate(alpha_value = ifelse(relevant>0,1,0.4))

p <- ggplot(data=df_output_combined) + geom_line(aes(x=DP_o, y=value, colour=col, linetype=claim_type, alpha=alpha)) +
  scale_linetype_manual(name = "", values=c(1,2), labels = c("Claim type 0","Claim type 1" ))+ 
  scale_colour_manual( values=c(
    c("grey","red", "blue")
    ),
    name =""
    )+
  scale_alpha_manual(
    values=c(alpha_vector$alpha_value),
    guide="none"
  )+
  ggtitle("LTRCTrees development factors") +
  xlab("Quarterly development period") + ylab("Development factor")+
  guides(col = guide_legend(reverse=T)) +
  theme_bw() +
  theme(legend.position=c(0.8,0.7),
        plot.title = element_text(hjust = 0.5,size = 10, face = "bold"),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.spacing.y = unit(0, "mm"),
        legend.background = element_blank(),
        legend.title = element_blank(),
        legend.box.background = element_rect(colour = "black"))
  
p



```



#Scoring functions
```{r eval=FALSE, include=FALSE}

resurv.predict <- readRDS("C:/Users/emil_/Downloads/12-17_cox_2023_05_25_09_55.RData")


full_data <- fread("C:/Users/emil_/OneDrive/Dokumenter/Uni/Speciale/R code/data/case_data_all_ng_12-17.csv")


scoring_function_case <-function(resurv.predict, full_data){

  conversion_factor <- resurv.predict$ReSurvFit$IndividualData$conversion_factor


  max_dp_i <-48

    #df_name <- paste0("case_data_train_ng_","12-17",".csv")
    #df <- read.csv(sprintf(path,df_name),header=T)
    df<- full_data %>%
        filter(DM <=48 &AM<=48)%>%
        mutate(CM=AM+DM-1)
    individual_data <- IndividualData(data = df,
                                    id=NULL,
                                    categorical_features = c("Claim_type_key", "Cover_key"),
                                    continuous_features = "AP_i",
                                    accident_period="AM",
                                    calendar_period="CM",
                                    input_time_granularity = "months",
                                    output_time_granularity = "quarters",
                                    continuous_features_spline=NULL,
                                    years=4 #check this. I see strange development periods
  )

    
#    resurv.predict <- predict(resurv.predict$ReSurvFit,
#                                  newdata=individual_data2,
#                             grouping_method = "probability")

  true_output <-individual_data$full.data %>%
    mutate(
      DP_rev_o = floor(max_dp_i*conversion_factor)-ceiling(DP_i*conversion_factor+((AP_i-1)%%(1/conversion_factor))*conversion_factor) +1,
      AP_o = ceiling(AP_i*conversion_factor),
      TR_o= AP_o-1
    ) %>%
    filter(DP_rev_o <=TR_o) %>%
    group_by(Claim_type_key,Cover_key,  AP_o, DP_rev_o) %>%
    mutate(Claim_type_key = as.character(Claim_type_key),
           Cover_key = as.character(Cover_key)
           ) %>%
    summarize(I=sum(I), .groups = "drop") %>%
    filter(DP_rev_o>0) #we cant have =0, because corresponds to half a parallelogram.

  #Total output
  score_total<- resurv.predict$hazard_frame_output[,c("Claim_type_key","Cover_key", "AP_o", "DP_rev_o", "I_expected")] %>%
    inner_join(true_output, by =c("Claim_type_key","Cover_key", "AP_o", "DP_rev_o")) %>%
    mutate(ave = I-I_expected,
           abs_ave = abs(ave))

  dfs_output <- resurv.predict$hazard_frame_output %>%
    select(AP_o, Claim_type_key, Cover_key, DP_rev_o, df_o) %>%
    mutate(DP_rev_o = DP_rev_o) %>% 
    distinct()

  #Cashflow on output scale.Etc quarterly cashflow development
  score_diagonal <- individual_data$full.data  %>%
    mutate(
      DP_rev_o = floor(max_dp_i*conversion_factor)-ceiling(DP_i*conversion_factor+((AP_i-1)%%(1/conversion_factor))*conversion_factor) +1,
      AP_o = ceiling(AP_i*conversion_factor)
    ) %>%
    group_by(Claim_type_key,Cover_key, AP_o, DP_rev_o) %>%
    mutate(Claim_type_key = as.character(Claim_type_key),
           Cover_key = as.character(Cover_key)) %>%
    summarize(I=sum(I), .groups = "drop") %>%
    group_by(Claim_type_key, Cover_key, AP_o) %>%
    arrange(desc(DP_rev_o)) %>%
    mutate(I_cum=cumsum(I)) %>%
    mutate(I_cum_lag = lag(I_cum, default = 0)) %>%
    inner_join(dfs_output, by = c("AP_o", "Claim_type_key", "Cover_key", "DP_rev_o")) %>%
    mutate(ave_2 =  I_cum-I_cum_lag * df_o,
           abs_ave_2 = abs(ave_2),
           RP_o = max(dfs_output$DP_rev_o)-DP_rev_o + AP_o) %>%
    inner_join(true_output[,c("AP_o", "DP_rev_o")] %>%  distinct()
               , by =c("AP_o", "DP_rev_o"))


  relative_total = sqrt(mean(score_total$ave^2*score_total$I/sum(score_total$I)))/sqrt(mean(score_total$I^2*score_total$I/sum(score_total$I)))
  RMSE_total = sqrt(mean(score_total$ave^2))

  relative_diagonal = score_diagonal %>% group_by(RP_o) %>%
    summarize(relative_diagonal = sqrt(sum(ave_2^2*I/sum(I),na.rm=T))/sqrt(sum(I^2*I/sum(I),na.rm=T)),
              I=sum(I))

  weighted_relative_diagonal = sum(relative_diagonal$relative_diagonal*relative_diagonal$I)/(sum(relative_diagonal$I))

  return(list(
    score_total = score_total,
    score_diagonal = score_diagonal,
    relative_diagonal = relative_diagonal,
    metrics =list(relative_total = relative_total,
    RMSE_total = RMSE_total,
    weighted_relative_diagonal = weighted_relative_diagonal
  )))
}

scoring_function_CL_case <- function(IndividualData, full_data, period){
  
  CL = IndividualData$training.data %>%
    mutate(DP_o = max(IndividualData$training.data$DP_rev_o)-DP_rev_o + 1) %>%
    group_by(AP_o, DP_o) %>%
    summarize(I=sum(I), .groups="drop") %>%
    group_by(AP_o) %>%
    arrange(DP_o) %>%
    mutate(I_cum = cumsum(I),
           I_cum_lag = lag(I_cum, default=0)) %>%
    ungroup() %>%
    group_by(DP_o) %>%
    reframe(df = sum(I_cum*(AP_o<=max(IndividualData$training.data$AP_o)-DP_o+1)) /
              sum(I_cum_lag*(AP_o<=max(IndividualData$training.data$AP_o)-DP_o+1)),
            I=sum(I*(AP_o<=max(IndividualData$training.data$AP_o)-DP_o))) %>%
    mutate(DP_o_join = DP_o) %>%
    mutate(DP_rev_o = max(DP_o) - DP_o +1 )
  
  CL<-expand.grid(DP_o_2=1:max(IndividualData$training.data$DP_rev_o)) %>% left_join(CL, , by=c("DP_o_2"="DP_o")) %>% 
    rename(DP_o = DP_o_2) %>% 
    replace_na(list(df=1))

  latest_observed <- IndividualData$training.data %>%
    filter(DP_rev_o >=TR_o) %>%
    mutate(DP_o = max(IndividualData$training.data$DP_rev_o)-DP_rev_o + 1) %>%
    group_by(AP_o) %>%
    mutate(DP_max =max(DP_o)) %>%
    group_by(AP_o, DP_max) %>%
    summarize(I=sum(I),.groups="drop")

  predictions <- expand.grid(AP_o = latest_observed$AP_o, DP_o = CL$DP_o_join) %>%
    left_join(CL[,c("DP_o", "df")], by=c("DP_o"="DP_o")) %>%
    left_join(latest_observed, by="AP_o") %>%
    rowwise() %>% 
    filter(DP_o>DP_max) %>%
    ungroup() %>% 
    group_by(AP_o) %>%
    arrange(DP_o) %>%
    mutate(df_cum = cumprod(df) ) %>%
    mutate(I_expected= I*df_cum-I*lag(df_cum,default=1)) %>%
    select(DP_o, AP_o, I_expected)

  conversion_factor = IndividualData$conversion_factor
  max_dp_i <- 48

  true_output_cl <- full_data$full.data %>%
    mutate(
      DP_rev_o = floor(max_dp_i*conversion_factor)-ceiling(DP_i*conversion_factor+((AP_i-1)%%(1/conversion_factor))*conversion_factor) +1,
      AP_o = ceiling(AP_i*conversion_factor),
      TR_o= AP_o-1
    ) %>%
    filter(DP_rev_o <=TR_o) %>%
    mutate(DP_o = max(IndividualData$training.data$DP_rev_o)-DP_rev_o + 1) %>%
    group_by(AP_o, DP_o, DP_rev_o) %>%
    summarize(I=sum(I), .groups="drop") %>%
    filter(DP_rev_o>0)

  score_total <- predictions  %>%
    inner_join(true_output_cl,
               by =c("AP_o", "DP_o")) %>%
    mutate(ave = I-I_expected,
           abs_ave = abs(ave))

  #calculate where we update with information from newest diagonal
  score_diagonal <- full_data$full.data  %>%
    mutate(
      DP_rev_o = floor(max_dp_i*conversion_factor)-ceiling(DP_i*conversion_factor+((AP_i-1)%%(1/conversion_factor))*conversion_factor) +1,
      AP_o = ceiling(AP_i*conversion_factor)
    ) %>%
    group_by( AP_o, DP_rev_o) %>%
    summarize(I=sum(I), .groups = "drop") %>%
    group_by(AP_o) %>%
    arrange(desc(DP_rev_o)) %>%
    mutate(I_cum=cumsum(I)) %>%
    mutate(I_cum_lag = lag(I_cum, default = 0)) %>%
     mutate(DP_o = max(IndividualData$training.data$DP_rev_o)-DP_rev_o + 1) %>%
    inner_join(CL[,c("DP_o","df")], by = c("DP_o")) %>%
    mutate(ave_2 = I_cum-I_cum_lag * df,
           abs_ave_2 = abs(ave_2),
           RP_o = max(DP_rev_o)-DP_rev_o + AP_o) %>%
    inner_join(true_output_cl[,c("AP_o", "DP_rev_o")] %>%  distinct()
               , by =c("AP_o", "DP_rev_o"))


   relative_total = sum(abs(score_total$abs_ave))/sum(score_total$I)
  RMSE_total = sqrt(mean(score_total$ave^2))

  relative_diagonal = score_diagonal %>% group_by(RP_o) %>%
    summarize(relative_diagonal = sqrt(sum(ave_2^2*I/sum(I),na.rm=T))/sqrt(sum(I^2*I/sum(I),na.rm=T)),
              I=sum(I))

  #weighted_relative_diagonal = sum(relative_diagonal$relative_diagonal*relative_diagonal$I)/(sum(relative_diagonal$I))
  
     
weighted_relative_diagonal <-(score_diagonal%>%
  group_by(AP_o,
           DP_rev_o,
           RP_o)%>%
  reframe(ave=sum((ave_2)), I=sum(I)) %>% 
  group_by(RP_o) %>% 
  mutate(diagonal.volume=sum(I)) %>%
  ungroup()%>%
  mutate(weight=I/diagonal.volume,
         squared.normalizer=(I^2))%>%
  ungroup()%>%
  group_by(
           RP_o) %>%
  reframe(diagonal_weight=sum(I),
          sqerr=sum(abs(ave)),
          sqnormalizer=sum(squared.normalizer*weight)) %>%
  ungroup() %>%
  reframe(diagonal.rmse= sum(sqerr*1/sum(diagonal_weight)) ))$diagonal.rmse
    
    
relative_total <-(score_total %>%
  mutate(RP_o = AP_o+max(dfs_output$DP_rev_o)-DP_rev_o,
         # abserr=abs(expected-actual),
        # sqerr=(ave)^2
        )%>%
  group_by(AP_o,
           DP_rev_o,
           RP_o)%>%
  reframe(ave=sum(abs(ave)), I=sum(I)) %>% 
  group_by(RP_o) %>% 
  mutate(diagonal.volume=sum(I)) %>%
  ungroup()%>%
  mutate(weight=I/diagonal.volume,
         squared.normalizer=(I^2))%>%
  ungroup()%>%
  group_by(
           RP_o) %>%
  reframe(diagonal_weight=sum(I),
          sqerr=sum(ave),
          sqnormalizer=sum(squared.normalizer*weight)) %>%
  ungroup() %>%
  reframe(diagonal.rmse= sum(sqerr*1/sum(diagonal_weight)) ))$diagonal.rmse

  
    scoring_result<- list(
    score_total = score_total,
    score_diagonal = score_diagonal,
    relative_diagonal = relative_diagonal,
    metrics =list(relative_total = relative_total,
                  RMSE_total = RMSE_total,
                  weighted_relative_diagonal = weighted_relative_diagonal
    ))
    
  # name = paste0("C:/Users/emil_/OneDrive/Dokumenter/Uni/Article/individual_clmplus/scores",  "/",period,"_CL_",format(Sys.time(), "%Y_%m_%d_%H_%M"),".RData")
  # saveRDS(scoring_result, file=name) 


  return(list(
    score_total = score_total,
    score_diagonal = score_diagonal,
    relative_diagonal = relative_diagonal,
    metrics =list(relative_total = relative_total,
                  RMSE_total = RMSE_total,
                  weighted_relative_diagonal = weighted_relative_diagonal
    )))

}

scoring_function_CL_case_input<-function(IndividualData, full_data, period){
  
CL = IndividualData$training.data %>%
  mutate(DP_i = max(IndividualData$training.data$DP_rev_i)-DP_rev_i + 1) %>%
  group_by(AP_i, DP_i) %>%
  summarize(I=sum(I), .groups="drop") %>%
  group_by(AP_i) %>%
  arrange(DP_i) %>%
  mutate(I_cum = cumsum(I),
         I_cum_lag = lag(I_cum, default=0)) %>%
  ungroup() %>%
  group_by(DP_i) %>%
  reframe(df = sum(I_cum*(AP_i<=max(IndividualData$training.data$AP_i)-DP_i+1)) /
            sum(I_cum_lag*(AP_i<=max(IndividualData$training.data$AP_i)-DP_i+1)),
          I=sum(I*(AP_i<=max(IndividualData$training.data$AP_i)-DP_i))) %>%
  mutate(DP_i_join = DP_i) %>%
  mutate(DP_rev_i = max(DP_i) - DP_i +1 )

CL<-expand.grid(DP_i_2=1:max(IndividualData$training.data$DP_rev_i)) %>% left_join(CL, , by=c("DP_i_2"="DP_i")) %>% 
  rename(DP_i = DP_i_2) %>% 
  replace_na(list(df=1))

latest_observed <- IndividualData$training.data %>%
  filter(DP_rev_i >=TR_o) %>%
  mutate(DP_i = max(IndividualData$training.data$DP_rev_i)-DP_rev_i + 1) %>%
  group_by(AP_i) %>%
  mutate(DP_max =max(DP_i)) %>%
  group_by(AP_i, DP_max) %>%
  summarize(I=sum(I),.groups="drop")

predictions <- expand.grid(AP_i = latest_observed$AP_i, DP_i = CL$DP_i_join) %>%
  left_join(CL[,c("DP_i", "df")], by=c("DP_i"="DP_i")) %>%
  left_join(latest_observed, by="AP_i") %>%
  rowwise() %>% 
  filter(DP_i>DP_max) %>%
  ungroup() %>% 
  group_by(AP_i) %>%
  arrange(DP_i) %>%
  mutate(df_cum = cumprod(df) ) %>%
  mutate(I_expected= I*df_cum-I*lag(df_cum,default=1)) %>%
  select(DP_i, AP_i, I_expected)

conversion_factor = IndividualData$conversion_factor
max_dp_i <- 48

true_output_cl <- full_data$full.data %>%
  filter(DP_rev_i <=TR_i) %>%
  group_by(AP_i, DP_i, DP_rev_i) %>%
  summarize(I=sum(I), .groups="drop") %>%
  filter(DP_rev_i>0)

score_total <- predictions  %>%
  inner_join(true_output_cl,
             by =c("AP_i", "DP_i")) %>%
  mutate(ave = I-I_expected,
         abs_ave = abs(ave))

#calculate where we update with information from newest diagonal
score_diagonal <- full_data$full.data  %>%
  group_by( AP_i, DP_rev_i) %>%
  summarize(I=sum(I), .groups = "drop") %>%
  group_by(AP_i) %>%
  arrange(desc(DP_rev_i)) %>%
  mutate(I_cum=cumsum(I)) %>%
  mutate(I_cum_lag = lag(I_cum, default = 0)) %>%
  mutate(DP_i = max(IndividualData$training.data$DP_rev_i)-DP_rev_i + 1) %>%
  inner_join(CL[,c("DP_i","df")], by = c("DP_i")) %>%
  mutate(ave_2 = I_cum-I_cum_lag * df,
         abs_ave_2 = abs(ave_2),
         RP_i = max(DP_rev_i)-DP_rev_i + AP_i) %>%
  inner_join(true_output_cl[,c("AP_i", "DP_rev_i")] %>%  distinct()
             , by =c("AP_i", "DP_rev_i"))


relative_total = sqrt(mean(score_total$ave^2*score_total$I/sum(score_total$I)))/sqrt(mean(score_total$I^2*score_total$I/sum(score_total$I)))
RMSE_total = sqrt(mean(score_total$ave^2))

relative_diagonal = score_diagonal %>% group_by(RP_i) %>%
  summarize(relative_diagonal = sqrt(sum(ave_2^2*I/sum(I),na.rm=T))/sqrt(sum(I^2*I/sum(I),na.rm=T)),
            I=sum(I))

#weighted_relative_diagonal = sum(relative_diagonal$relative_diagonal*relative_diagonal$I)/(sum(relative_diagonal$I))


weighted_relative_diagonal <-(score_diagonal%>%
                                group_by(AP_i,
                                         DP_rev_i,
                                         RP_i)%>%
                                reframe(ave=sum(abs(ave_2)), I=sum(I)) %>% 
                                group_by(RP_i) %>% 
                                mutate(diagonal.volume=sum(I)) %>%
                                ungroup()%>%
                                mutate(weight=I/diagonal.volume,
                                       squared.normalizer=(I^2))%>%
                                ungroup()%>%
                                group_by(
                                  RP_i) %>%
                                reframe(diagonal_weight=sum(I),
                                        sqerr=sum(ave*1),
                                        sqnormalizer=sum(squared.normalizer*weight)) %>%
                                ungroup() %>%
  reframe(diagonal.rmse= sum(sqerr*1/sum(diagonal_weight)) ))$diagonal.rmse


relative_total <-(score_total %>%
                    mutate(RP_i = AP_i+DP_i-1,
                           # abserr=abs(expected-actual),
                           # sqerr=(ave)^2
                    )%>%
                    group_by(AP_i,
                             DP_rev_i,
                             RP_i)%>%
                    reframe(ave=sum(abs(ave)), I=sum(I)) %>% 
                    group_by(RP_i) %>% 
                    mutate(diagonal.volume=sum(I)) %>%
                    ungroup()%>%
                    mutate(weight=I/diagonal.volume,
                           squared.normalizer=(I^2))%>%
                    ungroup()%>%
                    group_by(
                      RP_i) %>%
                    reframe(diagonal_weight=sum(I),
                            sqerr=sum(ave*1),
                            sqnormalizer=sum(squared.normalizer*weight)) %>%
                    ungroup() %>%
  reframe(diagonal.rmse= sum(sqerr*1/sum(diagonal_weight)) ))$diagonal.rmse


scoring_result<- list(
  score_total = score_total,
  score_diagonal = score_diagonal,
  relative_diagonal = relative_diagonal,
  metrics =list(relative_total = relative_total,
                RMSE_total = RMSE_total,
                weighted_relative_diagonal = weighted_relative_diagonal
  ))

return(scoring_result)
}


scoring_function <-function(resurv.predict){

  conversion_factor <- resurv.predict$ReSurvFit$IndividualData$conversion_factor


  max_dp_i <-1440


  true_output <- resurv.predict$ReSurvFit$IndividualData$full.data %>%
    mutate(
      DP_rev_o = floor(max_dp_i*conversion_factor)-ceiling(DP_i*conversion_factor+((AP_i-1)%%(1/conversion_factor))*conversion_factor) +1,
      AP_o = ceiling(AP_i*conversion_factor),
      TR_o= AP_o-1
    ) %>%
    filter(DP_rev_o <=TR_o) %>%
    group_by(claim_type, AP_o, DP_rev_o) %>%
    mutate(claim_type = as.character(claim_type)) %>%
    summarize(I=sum(I), .groups = "drop") %>%
    filter(DP_rev_o>0) #we cant have =0, because corresponds to half a parallelogram.

  #Total output
  score_total<- resurv.predict$hazard_frame_output[,c("claim_type","AP_o", "DP_rev_o", "I_expected")] %>%
    inner_join(true_output, by =c("claim_type","AP_o", "DP_rev_o")) %>%
    mutate(ave = I-I_expected,
           abs_ave = abs(ave))

  dfs_output <- resurv.predict$hazard_frame_output %>%
    select(AP_o, claim_type, DP_rev_o, df_o) %>%
    mutate(DP_rev_o = DP_rev_o) %>% 
    distinct()

  #Cashflow on output scale.Etc quarterly cashflow development
  score_diagonal <- resurv.predict$ReSurvFit$IndividualData$full.data  %>%
    mutate(
      DP_rev_o = floor(max_dp_i*conversion_factor)-ceiling(DP_i*conversion_factor+((AP_i-1)%%(1/conversion_factor))*conversion_factor) +1,
      AP_o = ceiling(AP_i*conversion_factor)
    ) %>%
    group_by(claim_type, AP_o, DP_rev_o) %>%
    mutate(claim_type = as.character(claim_type)) %>%
    summarize(I=sum(I), .groups = "drop") %>%
    group_by(claim_type, AP_o) %>%
    arrange(desc(DP_rev_o)) %>%
    mutate(I_cum=cumsum(I)) %>%
    mutate(I_cum_lag = lag(I_cum, default = 0)) %>%
    left_join(dfs_output, by = c("AP_o", "claim_type", "DP_rev_o")) %>%
    mutate(ave_2 =  I_cum-I_cum_lag * df_o,
           abs_ave_2 = abs(ave_2),
           RP_o = max(DP_rev_o)-DP_rev_o + AP_o) %>%
    inner_join(true_output[,c("AP_o", "DP_rev_o")] %>%  distinct()
               , by =c("AP_o", "DP_rev_o"))


  relative_total = sum(score_total$ave)/sum(score_total$I)
  RMSE_total = sqrt(mean(score_total$ave^2))

  relative_diagonal = score_diagonal %>% group_by(RP_o) %>%
    summarize(relative_diagonal = sum(ave_2,na.rm=T)/sum(I),
              I=sum(I))

  weighted_relative_diagonal = sum(relative_diagonal$relative_diagonal*relative_diagonal$I)/(sum(relative_diagonal$I))
  
      scoring_result<- list(
    score_total = score_total,
    score_diagonal = score_diagonal,
    relative_diagonal = relative_diagonal,
    metrics =list(relative_total = relative_total,
                  RMSE_total = RMSE_total,
                  weighted_relative_diagonal = weighted_relative_diagonal
    ))
      


  return(list(
    score_total = score_total,
    score_diagonal = score_diagonal,
    relative_diagonal = relative_diagonal,
    metrics =list(relative_total = relative_total,
    RMSE_total = RMSE_total,
    weighted_relative_diagonal = weighted_relative_diagonal
  )))
}

scoring_function_CL <- function(IndividualData){
  CL = IndividualData$training.data %>%
    mutate(DP_o = max(IndividualData$training.data$DP_rev_o)-DP_rev_o + 1) %>%
    group_by(AP_o, DP_o) %>%
    summarize(I=sum(I), .groups="drop") %>%
    group_by(AP_o) %>%
    arrange(DP_o) %>%
    mutate(I_cum = cumsum(I),
           I_cum_lag = lag(I_cum, default=0)) %>%
    ungroup() %>%
    group_by(DP_o) %>%
    reframe(df = sum(I_cum*(AP_o<=max(IndividualData$training.data$AP_o)-DP_o+1)) /
              sum(I_cum_lag*(AP_o<=max(IndividualData$training.data$AP_o)-DP_o+1)),
            I=sum(I*(AP_o<=max(IndividualData$training.data$AP_o)-DP_o))) %>%
    mutate(DP_o_join = DP_o) %>%
    mutate(DP_rev_o = max(DP_o) - DP_o +1 )

  latest_observed <- IndividualData$training.data %>%
    filter(DP_rev_o >=TR_o) %>%
    mutate(DP_o = max(IndividualData$training.data$DP_rev_o)-DP_rev_o + 1) %>%
    group_by(AP_o) %>%
    mutate(DP_max =max(DP_o)) %>%
    group_by(AP_o, DP_max) %>%
    summarize(I=sum(I),.groups="drop")

  predictions <- expand.grid(AP_o = latest_observed$AP_o, DP_o = CL$DP_o_join) %>%
    left_join(CL[,c("DP_o_join", "df")], by=c("DP_o"="DP_o_join")) %>%
    left_join(latest_observed, by="AP_o") %>%
    rowwise() %>% 
    filter(DP_o>DP_max) %>%
    ungroup() %>% 
    group_by(AP_o) %>%
    arrange(DP_o) %>%
    mutate(df_cum = cumprod(df) ) %>%
    mutate(I_expected= I*df_cum-I*lag(df_cum,default=1)) %>%
    select(DP_o, AP_o, I_expected)

  conversion_factor = IndividualData$conversion_factor
  max_dp_i <- 1440

  true_output_cl <- IndividualData$full.data %>%
    mutate(
      DP_rev_o = floor(max_dp_i*conversion_factor)-ceiling(DP_i*conversion_factor+((AP_i-1)%%(1/conversion_factor))*conversion_factor) +1,
      AP_o = ceiling(AP_i*conversion_factor),
      TR_o= AP_o-1
    ) %>%
    filter(DP_rev_o <=TR_o) %>%
    mutate(DP_o = max(IndividualData$training.data$DP_rev_o)-DP_rev_o + 1) %>%
    group_by(AP_o, DP_o, DP_rev_o) %>%
    summarize(I=sum(I), .groups="drop") %>%
    filter(DP_rev_o>0)

  score_total <- predictions  %>%
    inner_join(true_output_cl,
               by =c("AP_o", "DP_o")) %>%
    mutate(ave = I-I_expected,
           abs_ave = abs(ave))

  #calculate where we update with information from newest diagonal
  score_diagonal <- IndividualData$full.data  %>%
    mutate(
      DP_rev_o = floor(max_dp_i*conversion_factor)-ceiling(DP_i*conversion_factor+((AP_i-1)%%(1/conversion_factor))*conversion_factor) +1,
      AP_o = ceiling(AP_i*conversion_factor)
    ) %>%
    group_by(claim_type, AP_o, DP_rev_o) %>%
    mutate(claim_type = as.character(claim_type)) %>%
    summarize(I=sum(I), .groups = "drop") %>%
    group_by(claim_type, AP_o) %>%
    arrange(desc(DP_rev_o)) %>%
    mutate(I_cum=cumsum(I)) %>%
    mutate(I_cum_lag = lag(I_cum, default = 0)) %>%
     mutate(DP_o = max(IndividualData$training.data$DP_rev_o)-DP_rev_o + 1) %>%
    left_join(CL[,c("DP_o","df")], by = c("DP_o")) %>%
    mutate(ave_2 = I_cum-I_cum_lag * df,
           abs_ave_2 = abs(ave_2),
           RP_o = max(DP_rev_o)-DP_rev_o + AP_o) %>%
    inner_join(true_output_cl[,c("AP_o", "DP_rev_o")] %>%  distinct()
               , by =c("AP_o", "DP_rev_o"))


  relative_total = sum(score_total$ave)/sum(score_total$I)
  RMSE_total = sqrt(mean(score_total$ave^2))

  relative_diagonal = score_diagonal %>% group_by(RP_o) %>%
    summarize(relative_diagonal = sum(ave_2)/sum(I),
              I=sum(I))

  weighted_relative_diagonal = sum(relative_diagonal$relative_diagonal*relative_diagonal$I)/(sum(relative_diagonal$I))


  return(list(
    score_total = score_total,
    score_diagonal = score_diagonal,
    relative_diagonal = relative_diagonal,
    metrics =list(relative_total = relative_total,
                  RMSE_total = RMSE_total,
                  weighted_relative_diagonal = weighted_relative_diagonal
    )))

}
scores_cl <- expand.grid(sim=1:20, scenario=0:4) %>% tibble() %>%  mutate(relative_total=as.numeric(NA),
                    RMSE_total =as.numeric(NA),
                    cash_flow_quarterly=as.numeric(NA),
                    cash_flow_yearly=as.numeric(NA))
for(i in 1:20){
  print(i)
  for(j in 0:4){
    print(j)
input_data <- data_generator(random_seed = i,
                              scenario=j,
                              time_unit = 1/360,
                              years = 4,
                              yearly_exposure = 200)
  individual_data <- IndividualData(data = input_data,
                                    id=NULL,
                                    categorical_features = c("claim_type"),
                                    continuous_features = "AP_i",
                                    accident_period="AP",
                                    calendar_period="RP",
                                    input_time_granularity = "days",
                                    output_time_granularity = "years",
                                    years=4 #check this. I see strange development periods
  )
  score<-scoring_function_CL(individual_data)
  
          name = paste0("C:/Users/emil_/OneDrive/Dokumenter/Uni/Article/individual_clmplus/scores",  "/sim",j,"_",i,"_CL_yearly",format(Sys.time(), "%Y_%m_%d_%H_%M"),".RData")
  saveRDS(score, file=name) 
  # 
  # scores_cl[scores_cl$sim==i & scores_cl$scenario==j,]$RMSE_total <-score$metrics$RMSE_total
  # scores_cl[scores_cl$sim==i & scores_cl$scenario==j,]$relative_total <-score$metrics$relative_total
  # scores_cl[scores_cl$sim==i & scores_cl$scenario==j,]$cash_flow_quarterly <-score$metrics$weighted_relative_diagonal
  # 
  #   individual_data <- IndividualData(data = input_data,
  #                                   id=NULL,
  #                                   categorical_features = c("claim_type"),
  #                                   continuous_features = "AP_i",
  #                                   accident_period="AP",
  #                                   calendar_period="RP",
  #                                   input_time_granularity = "days",
  #                                   output_time_granularity = "years",
  #                                   years=4 #check this. I see strange development periods
  # )
  # score<-scoring_function_CL(individual_data)
  # 
  #  scores_cl[scores_cl$sim==i & scores_cl$scenario==j,]$cash_flow_yearly <-score$metrics$weighted_relative_diagonal
  }
}

scores_loc <- "C:/Users/emil_/OneDrive/Dokumenter/Uni/Article/individual_clmplus/scores"
#fwrite(scores_cl, paste0(scores_loc,"/sim_cl_2023_05_23_21_30.csv"))



periods <- c("12-17",
             "13-18",
             "14-19",
             "15-20",
             "16-21",
             "17-22")

path = "C:/Users/emil_/OneDrive/Dokumenter/Uni/Speciale/R code/data/%s"

scores_cl_case <- expand.grid(periods= periods) %>% tibble() %>%  mutate(relative_total=as.numeric(NA),
                    RMSE_total =as.numeric(NA),
                    cash_flow_quarterly=as.numeric(NA),
                    cash_flow_yearly=as.numeric(NA),
                    cash_flow_monthly = as.numeric(NA))

for(i in periods){
  print(i)
  
    df_name <- paste0("case_data_train_ng_",i,".csv")
    df <- read.csv(sprintf(path,df_name),header=T)
    df<- df %>%
        filter(DM <=48 &AM<=48)%>%
        mutate(CM=AM+DM-1)

    individual_data <- IndividualData(data = df,
                                    id=NULL,
                                    categorical_features = c("Claim_type_key", "Cover_key"),
                                    continuous_features = "AP_i",
                                    accident_period="AM",
                                    calendar_period="CM",
                                    input_time_granularity = "months",
                                    output_time_granularity = "quarters",
                                    continuous_features_spline="AP_i",
                                    years=4 #check this. I see strange development periods
  )

      df_name <- paste0("case_data_all_ng_",i,".csv")
    df <- read.csv(sprintf(path,df_name),header=T)
    df<- df %>%
        filter(DM <=48 &AM<=48)%>%
        mutate(CM=AM+DM-1)
    
      full_data <- IndividualData(data = df,
                                    id=NULL,
                                    categorical_features = c("Claim_type_key", "Cover_key"),
                                    continuous_features = "AP_i",
                                    accident_period="AM",
                                    calendar_period="CM",
                                    input_time_granularity = "months",
                                    output_time_granularity = "quarters",
                                    continuous_features_spline="AP_i",
                                    years=4 #check this. I see strange development periods
  )
  
  
    score<-scoring_function_CL_case(individual_data,full_data,i)
    score_input<-scoring_function_CL_case_input(individual_data,full_data,i)
    scores_cl_case[scores_cl_case$periods==i,]$cash_flow_monthly <-score_input$metrics$weighted_relative_diagonal
  
  scores_cl_case[scores_cl_case$periods==i,]$RMSE_total <-score$metrics$RMSE_total
  scores_cl_case[scores_cl_case$periods==i,]$relative_total <-score$metrics$relative_total
  scores_cl_case[scores_cl_case$periods==i,]$cash_flow_quarterly <-score$metrics$weighted_relative_diagonal

    df_name <- paste0("case_data_train_ng_",i,".csv")
    df <- read.csv(sprintf(path,df_name),header=T)
    df<- df %>%
        filter(DM <=48 &AM<=48)%>%
        mutate(CM=AM+DM-1)

    individual_data <- IndividualData(data = df,
                                    id=NULL,
                                    categorical_features = c("Claim_type_key", "Cover_key"),
                                    continuous_features = "AP_i",
                                    accident_period="AM",
                                    calendar_period="CM",
                                    input_time_granularity = "months",
                                    output_time_granularity = "years",
                                    continuous_features_spline="AP_i",
                                    years=4 #check this. I see strange development periods
  )

      df_name <- paste0("case_data_all_ng_",i,".csv")
    df <- read.csv(sprintf(path,df_name),header=T)
    df<- df %>%
        filter(DM <=48 &AM<=48)%>%
        mutate(CM=AM+DM-1)

      full_data <- IndividualData(data = df,
                                    id=NULL,
                                    categorical_features = c("Claim_type_key", "Cover_key"),
                                    continuous_features = "AP_i",
                                    accident_period="AM",
                                    calendar_period="CM",
                                    input_time_granularity = "months",
                                    output_time_granularity = "years",
                                    continuous_features_spline="AP_i",
                                    years=4 #check this. I see strange development periods
  )

  score<-scoring_function_CL_case(individual_data,full_data,i)

   scores_cl_case[scores_cl_case$periods==i,]$cash_flow_yearly <-score$metrics$weighted_relative_diagonal
  
  
}
fwrite(scores_cl_case, paste0(scores_loc,"/case_cl_2023_05_31.csv"))
```

# Standard code
``` {r eval=FALSE, include=FALSE}

resurv.predict<- readRDS("C:/Users/emil_/Downloads/13-18_xgboost_2023_05_23_14_11.RData")
scoring_function <-function(resurv.predict){

  conversion_factor <- resurv.predict$ReSurvFit$IndividualData$conversion_factor

  df <- fread("C:/Users/emil_/OneDrive/Dokumenter/Uni/Speciale/R code/data/case_data_all_ng_13-18.csv")
  df<- df %>%
  filter(DM <=48 &AM<=48)%>%
  mutate(CM=AM+DM-1)

  prova <- IndividualData(data = df,
                        id=NULL,
                        categorical_features = c("Claim_type_key"),
                        continuous_features = NULL,
                        accident_period="AM",
                        calendar_period="CM",
                        input_time_granularity = "months",
                        output_time_granularity = "quarters",
                        years=4 #check this. I see strange development periods
                        )
  
  max_dp_i <-48


  true_output <- prova$full.data %>%
    mutate(
      DP_rev_o = floor(max_dp_i*conversion_factor)-ceiling(DP_i*conversion_factor+((AP_i-1)%%(1/conversion_factor))*conversion_factor) +1,
      AP_o = ceiling(AP_i*conversion_factor),
      TR_o= AP_o-1
    ) %>%
    filter(DP_rev_o <=TR_o) %>%
    group_by(Claim_type_key,Cover_key, AP_o, DP_rev_o) %>%
    mutate(Claim_type_key = as.character(Claim_type_key), Cover_key=as.character(Cover_key)) %>%
    summarize(I=sum(I), .groups = "drop") %>%
    filter(DP_rev_o>0) #we cant have =0, because corresponds to half a parallelogram.

  #Total output
  score_total<- resurv.predict$hazard_frame_output[,c("Claim_type_key","Cover_key","AP_o", "DP_rev_o", "I_expected")] %>%
    inner_join(true_output, by =c("Claim_type_key","Cover_key","AP_o", "DP_rev_o")) %>%
    mutate(ave = I-I_expected,
           abs_ave = abs(ave))

  dfs_output <- resurv.predict$hazard_frame_output %>%
    select(AP_o, Claim_type_key,Cover_key, DP_rev_o, df_o) %>%
    mutate(DP_rev_o = DP_rev_o) %>% 
    distinct()

  #Cashflow on output scale.Etc quarterly cashflow development
  score_diagonal <- prova$full.data  %>%
    mutate(
      DP_rev_o = floor(max_dp_i*conversion_factor)-ceiling(DP_i*conversion_factor+((AP_i-1)%%(1/conversion_factor))*conversion_factor) +1,
      AP_o = ceiling(AP_i*conversion_factor)
    ) %>%
    group_by( Claim_type_key,Cover_key, AP_o, DP_rev_o) %>%
    mutate(Claim_type_key = as.character(Claim_type_key), Cover_key=as.character(Cover_key)) %>%
    summarize(I=sum(I), .groups = "drop") %>%
    group_by( Claim_type_key,Cover_key, AP_o) %>%
    arrange(desc(DP_rev_o)) %>%
    mutate(I_cum=cumsum(I)) %>%
    mutate(I_cum_lag = lag(I_cum, default = 0)) %>%
    left_join(dfs_output, by = c("AP_o", "Claim_type_key","Cover_key", "DP_rev_o")) %>%
    mutate(ave_2 =  I_cum-I_cum_lag * df_o,
           abs_ave_2 = abs(ave_2),
           RP_o = max(DP_rev_o)-DP_rev_o + AP_o) %>%
    inner_join(true_output[,c("AP_o", "DP_rev_o")] %>%  distinct()
               , by =c("AP_o", "DP_rev_o"))


  relative_total = sum(score_total$ave)/sum(score_total$I)
  RMSE_total = sqrt(mean(score_total$ave^2))

  relative_diagonal = score_diagonal %>% group_by(RP_o) %>%
    summarize(relative_diagonal = sum(ave_2,na.rm=T)/sum(I),
              I=sum(I))

  weighted_relative_diagonal = sum(relative_diagonal$relative_diagonal*relative_diagonal$I)/(sum(relative_diagonal$I))

  return(list(
    score_total = score_total,
    score_diagonal = score_diagonal,
    relative_diagonal = relative_diagonal,
    metrics =list(relative_total = relative_total,
    RMSE_total = RMSE_total,
    weighted_relative_diagonal = weighted_relative_diagonal
  )))
}

```


```{r eval=FALSE, include=FALSE}

# # # ## Model fit ----

resurv.cv.xgboost <- ReSurvCV(IndividualData=individual_data,
                               model="xgboost",
                               hparameters_grid=list(booster="gbtree",
                                             eta=c(.001,.01,.2,.3),
                                             max_depth=c(3,6,8),
                                             subsample=c(1),
                                             alpha=c(0,.2,1),
                                             lambda=c(0,.2,1),
                                             min_child_weight=c(.5,1)),
                               print_every_n = 1L,
                               nrounds=500,
                               verbose=F,
                               verbose.cv=T,
                               early_stopping_rounds = 100,
                               folds=5,
                               parallel=T,
                               ncores=2,
                               random_seed=1)

```


```{r}
# # # ## Model fit ----
#With parallel computing

resurv.cv.deep_surv_par <- ReSurvCV(IndividualData=individual_data,
                               model="deepsurv",
                               hparameters_grid=list(num_layers = c(10L),
                                                      num_nodes = c(10L),
                                                      optim=c("Adam"),
                                                      activation = "LeakyReLU",
                                                      lr=c(0.005),
                                                      xi=c(0.480269023349308),
                                                      eps = c(00),
                                                      tie = "Efron",
                                                      batch_size = c(as.integer(5000)),
                                                      early_stopping = 'TRUE',
                                                      patience  = 20
                                ),
                              epochs = as.integer(2),
                              num_workers = 0,
                              parallel = F,
                              ncores = 1,
                              verbose = T,
                              folds=2,
                              random_seed=1)





```


```{r}
# # # ## Model fit ----
# library(reticulate)
resurv.fit.deep_surv <- ReSurv(individual_data,
                          hazard_model = "deepsurv",
                          hparameters=list(num_layers=c(4),
                                          early_stopping = FALSE,
                                          patience = 20,
                                          network_structure = NULL,
                                          num_nodes = c(10),
                                          activation = "LeakyReLU",
                                          optim="Adam",
                                          lr = 0.005,
                                          xi=1,
                                          epsilon = 0,
                                          batch_size=as.integer(1000),
                                          epochs=as.integer(5),
                                          num_workers=0,
                                          tie="Efron"))



```



```{r}
# # # ## Model fit ----
resurv.fit.cox <- ReSurv(individual_data,
                          hazard_model = "cox")

```

```{r}
# # # ## Model fit ----
resurv.fit.xgboost <- ReSurv(individual_data,
                          hazard_model = "xgboost",
                          hparameters = list(params=list(booster="gbtree",
                                             eta=.01,
                                             subsample=.5,
                                             alpha=1,
                                             lambda=1,
                                             min_child_weight=.2),
                                             print_every_n = 1,
                                             nrounds=10,
                                             verbose=F,
                                             early_stopping_rounds = 500))

```


```{r}
# # # ## Model fit ----
resurv.fit.ltrctrees <- ReSurv(individual_data,
                               hazard_model = "LTRCtrees")

```
```{r eval=FALSE, include=FALSE}

# # # ## Model fit ----
resurv.cv.ltrctrees <- ReSurvCV(IndividualData=individual_data,
                               model="LTRCtrees",
                               hparameters_grid = list(
                                cp=c(0.0000000001,0.01),
                                 minbucket = c(1)),
                               folds=2,
                               random_seed=1,
                               verbose.cv = T)

```


```{r eval=FALSE, include=FALSE}

plot_data <-resurv.fit.deep_surv$hazard_frame_input %>% 
  select(AP_i, claim_type, DP_rev_i, df_i) %>% 
  distinct() 

ggplot(plot_data) +
  geom_point( aes(x=DP_rev_i, y=df_i, col=AP_i)) +
  facet_wrap(~claim_type, scales="free") +
  scale_colour_gradient(name="Accident period") +
  theme_bw() +
  scale_x_continuous(trans="reverse",
                     limits=c(48,40),
                     breaks = c(seq(from=48,to=40,by=-1)),
                     labels=c(seq(1,9,1))) +
  ggtitle("Accident period dependent development factors")+
  xlab("Development Period") +
  ylab("Development Factor")
  

```

```{r eval=FALSE, include=FALSE}

  
  
  #Score on output granuality
  individual_data <- IndividualData(input_data,
                                  id="claim_number",
                                  continuous_features="AP_i",
                                  categorical_features="claim_type",
                                  accident_period="AM",
                                  calendar_period="RM",
                                  input_time_granularity = "months",
                                  output_time_granularity = "quarters",
                                  years=4,
                                  continuous_features_spline=NULL)
  
resurv.fit <- ReSurv(individual_data,
                          hazard_model = "deepsurv",
                          hparameters=list(num_layers=c(4),
                                          early_stopping = FALSE,
                                          patience = 20,
                                          network_structure = NULL,
                                          num_nodes = c(10),
                                          activation = "LeakyReLU",
                                          optim="Adam",
                                          lr = 0.005,
                                          xi=1,
                                          epsilon = 0,
                                          batch_size=as.integer(1000),
                                          epochs=as.integer(10),
                                          num_workers=0,
                                          tie="Efron"))
  
resurv.fit <- 

  
  
conversion_factor <- resurv.fit$IndividualData$conversion_factor

  true_output <- resurv.fit$IndividualData$full.data %>%
    filter(DP_rev_i <= TR_i) %>%
    mutate(
      DP_rev_o = floor(max(DP_i)*conversion_factor)-ceiling(DP_i*conversion_factor+((AP_i-1)%%(1/conversion_factor))*conversion_factor) +1,
      AP_o = ceiling(AP_i*conversion_factor)
    ) %>%
    group_by(claim_type, AP_o, DP_rev_o) %>%
    mutate(claim_type = as.character(claim_type)) %>%
    summarize(I=sum(I), .groups = "drop")

  score_data <- resurv.fit$hazard_frame_output[,c("claim_type","AP_o", "DP_rev_o", "I_expected")] %>%
    inner_join(true_output, by =c("claim_type","AP_o", "DP_rev_o")) %>%
    mutate(ave = I-I_expected,
           abs_ave = abs(ave))
  

  sum(score_data$ave)
  sum(score_data$abs_ave)
  
  #chain ladder
  CL = resurv.fit$IndividualData$training.data %>% 
    mutate(DP_o = max(resurv.fit$hazard_frame_output$DP_rev_o)-DP_rev_o + 1) %>% 
    group_by(AP_o, DP_o) %>% 
    summarize(I=sum(I), .groups="drop") %>%  
    group_by(AP_o) %>%
    arrange(DP_o) %>% 
    mutate(I_cum = cumsum(I),
           I_cum_lag = lag(I_cum, default=0)) %>% 
    ungroup() %>% 
    group_by(DP_o) %>% 
    reframe(df = sum(I_cum*(AP_o<=max(resurv.fit$IndividualData$training.data$AP_o)-DP_o+1)) /
            sum(I_cum_lag*(AP_o<=max(resurv.fit$IndividualData$training.data$AP_o)-DP_o+1)),
              I=sum(I*(AP_o<=max(resurv.fit$IndividualData$training.data$AP_o)-DP_o))) %>% 
    mutate(DP_o_join = DP_o-1)
  
  latest_observed <- resurv.fit$IndividualData$training.data %>% 
    mutate(DP_o = max(resurv.fit$hazard_frame_output$DP_rev_o)-DP_rev_o + 1) %>% 
    group_by(AP_o) %>% 
    mutate(DP_max =max(DP_o)) %>% 
    group_by(AP_o, DP_max) %>% 
    summarize(I=sum(I),.groups="drop")
    
  predictions <- expand.grid(AP_o = latest_observed$AP_o, DP_o = CL$DP_o_join) %>% 
    left_join(CL[,c("DP_o_join", "df")], by=c("DP_o"="DP_o_join")) %>% 
    left_join(latest_observed, by="AP_o") %>% 
    group_by(AP_o) %>% 
    filter(DP_o>=DP_max) %>% 
    arrange(DP_o) %>% 
    mutate(df_cum = cumprod(df) ) %>% 
    mutate(I_expected= I*df_cum-I*lag(df_cum,default=1)) %>% 
    mutate(DP_o = DP_o +1) %>% 
    select(DP_o, AP_o, I_expected)
  
  
  true_output_cl <- true_output %>%
                 mutate(DP_o = max(resurv.fit$hazard_frame_output$DP_rev_o)-DP_rev_o + 1) %>% 
    group_by(AP_o, DP_o) %>% 
    summarize(I=sum(I), .groups="drop")
   
  score_data_CL <- predictions  %>%
    inner_join(true_output_cl,
               by =c("AP_o", "DP_o")) %>%
    mutate(ave = I-I_expected,
           abs_ave = abs(ave))
  
  sum(score_data_CL$ave)
  sum(score_data_CL$abs_ave)

```








