# Vector of variables
# This script contains the global variables we define to ease the package computations.

vector_of_variables <- c("DP_i",
                         "AP_i",
                         "DP_rev_i",
                         "TR_i",
                         "AP_o",
                         "DP_rev_o",
                         "TR_o",
                         'RP_i',
                         'degree_cp',
                         "years",
                         "time_unit",
                         "p_month",
                         "time_w",
                         "weight",
                         "is_lkh",
                         "k",
                         "hazard",
                         "risks_s",
                         "events_s",
                         "ties",
                         "feature",
                         "value",
                         "IBNR",
                         "ix_group",
                         "S_i",
                         ".",
                         "id",
                         "expg",
                         "baseline",
                         "group_i",
                         "f_i",
                         "df_i",
                         "dev_f_i",
                         "group_o",
                         "cum_dev_f_i",
                         "cum_f_i",
                         "DP_o",
                         "f_o",
                         "df_o",
                         "I_expected")

utils::globalVariables(c(vector_of_variables,
  # Column names and parent-scope selectors used in data.table/dplyr expressions.
  "..columns_for_grouping", "..eta", "AP", "AP_i_tmp", "AT", "C", "CP",
  "DP", "DP_i_tmp", "DP_max_rev", "DP_max_rev_keep", "DP_o_max", "DP_rev",
  "I_combined", "I_help", "I_new", "RP", "RP_i_tmp", "RP_o", "RT",
  "S_i_lag", "S_i_lead", "S_ultimate_i", "U", "actual", "age", "age_cont",
  "age_effect", "claim_number", "claim_type", "covariate", "crps",
  "crps_group", "delay", "delta", "dev_f_o", "df_i_adjusted", "exposure",
  "exposure_combined", "exposure_expected", "f", "features.id", "gm",
  "i.exposure", "i.group_o", "id_crps", "latest_I", "n_claims", "new",
  "num_layers", "num_nodes", "obs_DP_rev_i", "observed", "phi", "term",
  "variable"
))
